#pragma once

#define FUSION_BUFFER_SIZE_MB "FUSION_BUFFER_SIZE_MB"
#define COMPRESSION_MINIMAL_SIZE "COMPRESSION_MINIMAL_SIZE"
#define COMPRESSION_QUANTIZATION_BITS "COMPRESSION_QUANTIZATION_BITS"
#define COMPRESSION_BUCKET_SIZE "COMPRESSION_BUCKET_SIZE"
#define COMPRESSION_SKIP_INCOMPLETE_BUCKETS "COMPRESSION_SKIP_INCOMPLETE_BUCKETS"

const int FUSION_SIZE_DEFAULT_MB = 64;