name: Build CGX
on: [pull_request]
jobs:
  Build:
    runs-on: ubuntu-latest
    container: nvidia/cuda:12.6.3-devel-ubuntu24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: apt update && apt install -y libopenmpi-dev python3 python3.12-venv python3-dev
      - name: Setup venv
        shell: bash
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install setuptools build ninja
          pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126
      - name: Run build
        shell: bash
        run: |
          source .venv/bin/activate
          export NCCL_INCLUDE=/usr/include/
          export NCCL_LIB=/usr/lib/
          export MPI_HOME=/usr/lib/x86_64-linux-gnu/openmpi/
          python3 -m build --wheel --no-isolation
